name: Build VueApp

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set project as pages
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'MekouRaouf'
        reponame: 'test_actions'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install

    - run: npm ci

    - run: npm run build